### ISSUE TITLE
Unable to specify RDP port

### ISSUE THREAD

**Issue by trondhindenes** [lstratman/EasyConnect#59]
Need to be able to specify the RDP port of the target computer.

**Comment by xxxmtixxx** [comment]
I would also like the ability to specify the RDP port. If specified, the tab automatically closes after trying to connect to the target computer. Without specifying, the tab opens but times out due the target machine having a non-standard RDP port.

**Comment by peterquest** [comment]
Not being able to specify ports is somewhat of a dealbreaker. If I get a chance I'll try to contribute..

**Comment by ademiry** [comment]
+1 for adding ports
