### ISSUE TITLE
Support of Network Level Authentication

### ISSUE THREAD

**Issue by stefer** [lstratman/EasyConnect#61]
Hi,

I am evaluating EasyConnect to use instead of Remote Desktop Manager.

I get this message when trying to connect to a Windows server 2012:
"The remote computer requires Network Level Authentication, which your computer does not support"

I can connect to the computer using Windows 7 remote desktop and using Remote Desktop Manager, so it seem to be a problem unique to EasyConnect.

// Stefan

**Comment by stefer** [comment]
Strange, as far as I can see, you should already have this implemented. The NLA settings are enabled.
I have EasyConnect version 1.5.1.0, running from a Windows 7 with a mstscax.dll version 6.3.9600.17276 in the system32 folder.

Why does EasyConnect not work when my remote desktop works?

**Comment by lstratman** [comment]
Yeah, it has been implemented, just not packaged into a release. I was waiting to implement a few more things before creating a formal release, but I've fallen behind a bit on that. If you want to simply compile from the current code, that will give you what you need, otherwise I'll create a new release in the next few days.

**Comment by stefer** [comment]
Aha, that is great news.

I will see if I get get some free time and perhaps help out with the
project. There are a few things I think is missing, like inherited
settings, and it would be fun to contribute.

/ Stefan

mån 3 aug 2015 23:48 Luke Stratman <notifications@github.com> skrev:

**Comment by RoyOMiller** [comment]
I just encountered the same problem running v1.5.1.0, any news on an updated version that includes the fix?

**Comment by 935main** [comment]
Had the same issue - is the recommendation to just build from source manually still the way to go?

**Comment by Chazeo** [comment]
Hi All

Any update on this ? Does anyone perhaps have a working compiled version ?

**Comment by kelan236** [comment]
Hi Luke,  
I am experiencing the same issues here on 1.5.1.0 as well.  I noticed in the last couple weeks you've been committing some updates to the project.  Any chance we'll see a new version released in the near future?  By the way, great program, I love the Chrome-like interface!  It's so clean and minimal.  Thanks, have a great day!

**Comment by lstratman** [comment]
@kelan236, I am indeed planning to package a new installer in the (hopefully very) near future.  I'm trying to get a few issues sorted out with the new SSH terminal control and then it should be good to go.

**Comment by SteveCliff** [comment]
@lstratman - looking forward to a new release with NLA supported - most of my virtual machines have NLA enabled :)

**Comment by lstratman** [comment]
A new version of EasyConnect is **finally** up and available for download at: http://lstratman.github.io/EasyConnect/updates/EasyConnect.msi

**Comment by SteveCliff** [comment]
INstalled the new version - bang, straight in to my server using NLA - nice one! :)
