### ISSUE TITLE
Does not support XP?

### ISSUE THREAD

**Issue by zbooa** [lstratman/EasyConnect#62]
It can be compiled in XP+VS2010, but can not run, prompt
"Unable to find entry point called" SetWindowThemeAttribute "in DLL" uxtheme.dll ". "
Does not support XP?

**Comment by lstratman** [comment]
I appreciate the suggestion, but I won't be pursuing this since XP has been out of official support from Microsoft for quite a while.  If anyone ever wants to do this via a PR, feel free and I can re-open this.
