### ISSUE TITLE
Error on connect

### ISSUE THREAD

**Issue by profbaco** [lstratman/EasyConnect#66]
The system, now that it has fixed a port, does not connect more to some TSs. There are clients whose port number is 33399 and this update is not letting you put ports above 32167
Anyone who uses RDP protocols is no longer able to access. Anything sends me a private message that I send the IP to you to do a test and see that UltraRDP nor EasyConnect connects in some IP's
================================================
O sistema, agora que fixou uma porta, não faz conexão mais com alguns TS. Existem clientes cuja a porta é número 33399 e esta atualização não esta deixando colocar portas acima de 32167
Quem utiliza regra de protocolos RDP não está mais conseguindo acessar. Qualquer coisa me manda uma mensagem privada que te mando o IP para vc fazer um teste e ver que o UltraRDP nem o EasyConnect conecta em alguns IP´s

**Comment by lstratman** [comment]
I've put a new version up at http://lstratman.github.io/EasyConnect/updates/EasyConnect-2.0.1.msi that uses a simple text box instead of the spinner to capture the port number, which should resolve your issue.  Can you let me know if this does the trick?

**Comment by profbaco** [comment]
Okay, with this new update worked. You are now connecting normally. Thank you
========================================
Ok, com essa nova atualização funcionou. Agora esta conectando normalmente. Obrigado
