### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by profbaco** [lstratman/EasyConnect#67]
Suggestion:
Would you put a TEXT or MEMO field for TS observation? It would be interesting to make TS specific notes
=============================================
Sugestão:
Teria como colocar um campo TEXT ou MEMO para observação do TS? Seria interessante para fazer anotações específicas de determinardo TS

**Comment by lstratman** [comment]
Thank you for the suggestion, this is being handled by #55, which will be part of the next release.
