### ISSUE TITLE
All characters I type end up uppercase

### ISSUE THREAD

**Issue by yecril71pl** [lstratman/EasyConnect#75]
It is impossible to do anything in the shell because everything is uppercase, Shift or no Shift.  Pressing Caps Lock emits a bell.

**Comment by lstratman** [comment]
This probably has something to do with the encoding used with the SSH connection.  I've released a new build at http://lstratman.github.io/EasyConnect (may take up to 24 hours to show up if you installed it through the Microsoft Store) that allows you to specify the encoding type for the connection in the connection's option page (it defaults to UTF-8).  Try setting that to whatever encoding type is used by your server and, if you still run into issues, let me know what that encoding type was and I will research further.

**Comment by yecril71pl** [comment]
I mean VNC here.

**Comment by lstratman** [comment]
Sorry for the delay, I've just gotten back into developing for this project.  The issue that you were seeing was the result of the VNC client library that I was using.  I've switched to another library for the upcoming 3.0 version which I will be releasing in a few days.  For the 3.1 release, I plan on re-writing the VNC support to be build on libvncserver, which gives us access to a wider set of RFB encoding, TLS support, etc.

**Comment by lstratman** [comment]
Finally got time to finish the VNC rewrite, which is up on the download site, the Microsoft Store, and on winget.  The VNC plugin now uses a new library ([MarcusW.VncClient](https://github.com/MarcusWichelmann/MarcusW.VncClient)), which solves the key mapping issues that you were seeing here.  It's been tested against Ubuntu, Windows, and MacOS VNC servers.
