### ISSUE TITLE
SSH Port #

### ISSUE THREAD

**Issue by Wolfereign** [lstratman/EasyConnect#76]
How do I set the SSH port number?  Or better yet a default SSH port number.

**Comment by fernandogobah** [comment]
???

**Comment by lstratman** [comment]
Sorry for the delay, I was heads down on a project at work and let my backlog for EasyConnect get away from me.  The ability to specify an SSH port has been in the codebase for a while, but I just hadn't done a release build to actually expose that functionality.  That release build is now done, so you can either download the new MSI from http://lstratman.github.io/EasyConnect or, if you installed it from the Microsoft Store, you'll see an update for the app show up in the next 24 hours.
