### ISSUE TITLE
Unsupport pixel format

### ISSUE THREAD

**Issue by byroniac** [lstratman/EasyConnect#80]
Trying to use the Windows 10 Store app at work to connect to a TightVNC 2.8.8 server on Windows 7, and I am getting an error message of Unsupported Pixel format.

**Comment by lstratman** [comment]
Sorry for the delay, I've just gotten back into developing for this project.  The issue that you were seeing was the result of the VNC client library that I was using.  While the upcoming 3.0 release that is being published in the next few days will focus on updating the UI and fixing some other issues, for the 3.1 release, I plan on re-writing the VNC support to be build on libvncserver, which gives us access to a wider set of RFB encoding, TLS support, etc.  That should fix this issue.

**Comment by MarcusWichelmann** [comment]
@lstratman Hi, BTW I've developed a new VNC-Client library for C# that's fully-managed, very fast, cross-platform and way more advanced than Remoteviewing. Maybe you would like to use that instead: https://github.com/MarcusWichelmann/MarcusW.VncClient

Rendering can happen through a IRenderTarget interface which you could implement however you like. Just see the sample implemetations for Avalonia UI.

I'm also planning to add a ready-to-use control for Windows Forms to make things even easier, but that has not happened yet.

**Comment by lstratman** [comment]
This is exactly what I need, thanks!  I'll definitely check this out.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lstratman** [comment]
Finally got time to finish the VNC rewrite, which is up on the download site, the Microsoft Store, and on winget.  The VNC plugin now uses @MarcusWichelmann's library ([MarcusW.VncClient](https://github.com/MarcusWichelmann/MarcusW.VncClient)), which fixes the unsupported pixel format issue you were seeing.  It's been tested against Ubuntu, Windows, and MacOS VNC servers.

**Comment by MarcusWichelmann** [comment]
@lstratman Very cool! I just looked through your commits and it's very nice to see how you integrated it with Windows Forms. I also just saw your pull request and will look into it shortly. (Didn't get the GitHub notification, sorry for the delay.)
