### ISSUE TITLE
Add Telnet support

### ISSUE THREAD

**Issue by julianreichinger** [lstratman/EasyConnect#81]
While not that common anymore, Telnet is still used (for example to talk to OSGi) and would be a nice addition to the standard plug-ins.

**Comment by lstratman** [comment]
Sorry for the delay, I've just gotten back to developing for this project.  While the upcoming 3.0 release is going to focus on updating the UI and fixing some other issues, I plan on adding telnet support for the 3.1 release after that.

**Comment by lstratman** [comment]
Finally got time to writing a Telnet plugin for the latest version, which is up on the download site, the Microsoft Store, and on winget.
