### ISSUE TITLE
Error after Importing ecx file and accessing server

### ISSUE THREAD

**Issue by nickrobbo** [lstratman/EasyConnect#83]
Hi, 

I get the following error after I setup easyconnect on a new laptop. I imported a .ecx file and now I get this when trying to access a server.

![image](https://user-images.githubusercontent.com/35219805/45381527-72ab9180-b5fd-11e8-9f7b-6448d0dc4656.png)

**Comment by MythicalIceDragon** [comment]
I have the same problem with windows 10 after i turned off my recent documents

**Comment by nickrobbo** [comment]
Hi @MythicalIceDragon  - does enabling them again help?

**Comment by MythicalIceDragon** [comment]
yes it does. But i preffer it off. Looks more lik ethe error handling isnt made for this setting

**Comment by nickrobbo** [comment]
Right I see, yeah I prefer it off as well.  I will continue to use RemoteDesktopManagerFree, not sure if this will be resolved any time soon.

**Comment by lstratman** [comment]
Sorry for the delay, I just got back to developing for this project.  I've updated EasyConnect to not error out when trying to add jump list items when recent document tracking was turned off.  This will be in the 3.0 version which I will be publishing in the next few days.

**Comment by lstratman** [comment]
The 3.0 release just dropped and this should be fixed:  you should be able to use EasyConnect with recent document tracking turned off without errors.
