### ISSUE TITLE
Make available for linux (Disponibilizar para Linux)

### ISSUE THREAD

**Issue by profbaco** [lstratman/EasyConnect#84]
Hello, is there a possibility to run it inside linux? Do you have a condition or situation to use it?
-------------------------------
Olá, existe a possibilidade de executar ele dentro do linux? Tem alguma condição ou situação para utilizá-lo?

**Comment by lstratman** [comment]
Unfortunately, it's impossible with the application's current architecture.  Everything's in .NET, the RDP functionality relies on a lot of Windows-specific components, the tabs UI are all Windows-specific, etc.

Sorry :(
