### ISSUE TITLE
EasyConnect password protection broke

### ISSUE THREAD

**Issue by MateuszGrabuszynski** [lstratman/EasyConnect#86]
Hello,

I set EasyConnect password at the moment of the installation a while ago, and it does not work anymore - the prompt I get is that the password is incorrect. The password I set is known to me, I got it in saved in password manager and know it by heart as well, tried typing manually, copying from the manager and auto-type. I am 100% sure, I have not changed it as well.

Is there any file I can remove, a registry I can change or something else I can do to remove the previously set password (I do not bother about 3 saved addresses I had, they can be removed) and use the program as before? I tried re-installing and it did not help. I found EasyConnect really useful, and struggle using Windows RDP now.

**Comment by VShawn** [comment]
hey man, inviting you for try and help test my RDP/SSH management utility that makes launching remote sessions very convenient and fast. Any of your advice or report is priceless 😄.
https://github.com/VShawn/PRemoteM
