### ISSUE TITLE
How do I export easyconnect bookmarks?

### ISSUE THREAD

**Issue by mikkecm** [lstratman/EasyConnect#92]
Hello
How do I export easyconnect bookmarks?

**Comment by profbaco** [comment]
In the Bookmarks folder, right-click on favorites and choose the EXPORT option
=================
Na pasta Bookmarks, clique com o lado direito do mouse em cima de favoritos e escolha a opção EXPORTAR

**Comment by mikkecm** [comment]
Thank you
