### ISSUE TITLE
Key bindings using VNC (Windows to OSX)

### ISSUE THREAD

**Issue by raisindetre** [lstratman/EasyConnect#99]
When remotely connecting to a Mac OSX system using EasyConnect from Windows 10, not all special keys map as expected. The left and right Control keys map to OSX Ctrl which is fine but the Windows, L-Alt, R-Alt and Print key all map to the OSX Command key.  There doesn't appear to be a key binding for the Mac Option (Alt) key. Also, the special keys behave in a sticky mode (i.e. need to be toggled off and on). Is there a way of configuring the app to emulate certain OSX key presses?

**Comment by lstratman** [comment]
The most recent version now features a re-written VNC plugin that should solve any key mapping issues you were experiencing before.  The Alt key continues to be bound to the OSX Command key and the Menu key on your keyboard is bound to the OSX Option key.  I tried to keep it consistent with the key bindings for the RealVNC Viewer so most people would have an easy time moving over to EasyConnect.

Also, the sticky mode issue you were experiencing before should no longer happen.

**Comment by raisindetre** [comment]
Good to know. Is this version available via the Microsoft Store? I’m in a managed environment so can only install from there. I installed the version displaying this issue about 6-10 weeks ago.

**Comment by lstratman** [comment]
Yes, it's up in the store.

**Comment by raisindetre** [comment]
Thanks - this is working a lot better, the Command and Control keys are now working, however the Windows menu key (standard US Microsoft keyboard) does not appear to be mapped to themenu key. According to this RealVNC page, the Right Alt key is the key mapped to the OSX Option key. I'm not sure the menu key has any mapping?
